### PR TITLE
Update Readme.mdown

### PR DESCRIPTION
**Pull request by paulkoegel**
Show us that pretty GIF!

### CODE REVIEW

**Comment by bumi** [comment]
hmm... not sure if this is an enhancement or if that is rather a reason not to use it. :)

**Comment by paulkoegel** [comment]
Show us that pretty gif!!!!
gifgifgifgifgifgifgifgifgifgifgifgifgifgifgifgifgifgifgifgifgifgifgifgif

**Comment by bumi** [comment]
let's see if somebody else is voting on it. :D

**Comment by DonSchado** [comment]
merge it!

**Comment by mortro** [comment]
:+1: too awesome to hide :wink:

**Comment by tmschndr** [comment]
:+1:

**Comment by yoyostile** [comment]
:+1:

**Comment by bumi** [comment]
kann man das bild noch was kleiner machen?

**Comment by paulkoegel** [comment]
ich hab das benutzt: http://ezgif.com/resize

**Pull request merged**
